name: Deploy to Netlify

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build & Deploy to Netlify
        uses: netlify/build@v4 # Use netlify/build@v4 
        with:
          # The name of the Netlify site to deploy to.
          site: https://onlineludo.netlify.app # Use site instead of site_id
          # The access token used to deploy to Netlify.
          token: ${{ secrets.NETLIFY_AUTH_TOKEN }} # No need for publish_dir here
